Repository logdna/logdna-agent, pull requests merged in 2019-11, with the labels that each got.

#136 update continuous testing
  .circleci/config.yml
  .travis.yml
  Gruntfile.js
  appveyor.yml
  lib/get-distro.js
  package.json
  test/lib/get-distro.js
Labels: enhancement

#135 retry on receiving 5xx
  lib/config.js
  lib/linebuffer.js
Labels: enhancement

#137 update user-agent header by adding distro information
  index.js
  lib/config.js
Labels: enhancement

#139 update failure condition and debug statements
  lib/linebuffer.js
Labels: bugfix

#138 autobuild for debian and redhat
  .circleci/config.yml
  .gitignore
  scripts/linux/after-upgrade
  scripts/linux/before-remove
  scripts/linux/init-script
  scripts/linux/logrotate
Labels: enhancement

#134 update custom logger
  Gruntfile.js
  index.js
  lib/connection-manager.js
  lib/file-utilities.js
  lib/get-distro.js
  lib/k8s.js
  lib/tailreadstream/tailreadstream.js
  lib/utils.js
  lib/welp.js
  lib/windows-utilities.js
Labels: enhancement

#140 update retry mechanism
  lib/connection-manager.js
  lib/linebuffer.js
Labels: bugfix, enhancement

#142 Update User-Agent Header
  index.js
  lib/config.js
  lib/get-distro.js
  lib/get-os.js
  test/assets/test-getDistro.config
  test/lib/get-distro.js
Labels: enhancement

#143 Handle 207 better
  lib/config.js
  lib/connection-manager.js
  lib/linebuffer.js
Labels: enhancement

#141 Add RBAC yaml & ensure agent yamls are consistent
  logdna-agent-ds-master.yaml
  logdna-agent-ds-os.yaml
  logdna-agent-ds.yaml
  logdna-agent-v2.yaml
  rbac.yaml
Labels: bugfix, enhancement

#145 Automate LogDNA Agent Release Pipeline
  .circleci/config.yml
  .gitignore
  index.js
  package.json
  scripts/etc/files/logdna-agent
  scripts/etc/files/logdna-agent.1
  scripts/etc/files/logdna.gpg
  scripts/etc/files/openrc-init
  scripts/etc/version.sh
  scripts/linux/build.sh
  scripts/linux/deploy.sh
  scripts/linux/files/after-upgrade
  scripts/linux/files/before-remove
  scripts/linux/files/init-script
  scripts/linux/files/logrotate
  scripts/linux/test.sh
Labels: enhancement
