Repository logdna/logdna-agent, pull requests merged in 2020-10, with the labels that each got.

#199 config: upgrade node version to v12.16.2
  README.md
  index.js
  package.json
  tools/README.md
  tools/files/win32/logdna-agent.nuspec
  tools/scripts/darwin.sh
  tools/scripts/debian.sh
  tools/scripts/redhat.sh
  tools/scripts/win32.sh
Labels: enhancement

#172 Added instructions to set up log forwarding for Fedora CoreOS
  README.md
Labels: k8s, linux

#210 [Duplicate] Use systemd service name as the app name
  lib/file-utilities.js
Labels: duplicate, enhancement, linux
